app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use App\Models\Photos\LocationPhoto as Photo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Jenssegers\Date\Date;
use App\Services\Trainings\Interval;

/**
 * App\Models\Location
 *
 * @property-read Collection|Photo[] $photos
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property float $longitude
 * @property float $latitude
 * @property string $description
 * @property string $season
 * @property string $short_name
 * @property string $icon
 * @property string $address
 * @property Date $period_start_date
 * @property Date $period_end_date
 * @property bool $has_interval
 */
class Location extends Model
{
    use Scopes\PhotoOwner, SoftDeletes;

    protected $table = 'location';

    protected $fillable = [
        'name',
        'short_name',
        'longitude',
        'latitude',
        'description',
        'season',
        'address',
        'period_start_date',
        'period_end_date',
    ];

    protected $visible = [
        'short_name',
        'season',
        'icon',
        'interval',
    ];

    public $timestamps = false;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|Builder
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * @return string
     */
    public function getIconAttribute(): string
    {
        return sprintf('/image/%s.png', $this->season === 'winter' ? 'snowflake' : 'sun');
    }

    /**
     * @return string
     */
    public function getNewIconAttribute(): string
    {
        return $this->season === 'winter' ? 'snow' : 'sun';
    }

    /**
     * @return string
     */
    public function getFormattedPeriodStartDateAttribute(): string
    {
        return $this->period_start_date
            ? $this->period_start_date->format('d.m')
            : '';
    }

    /**
     * @return string
     */
    public function getFormattedPeriodEndDateAttribute(): string
    {
        return $this->period_end_date
            ? $this->period_end_date->format('d.m')
            : '';
    }

    /**
     * @return bool
     */
    public function getHasIntervalAttribute(): bool
    {
        return !!$this->period_start_date && !!$this->period_end_date;
    }

    /**
     * @return null|Interval
     */
    public function getInterval(): ?Interval
    {
        if ($this->has_interval) {
            return new Interval(
                $this->period_start_date->month,
                $this->period_start_date->day,
                $this->period_end_date->month,
                $this->period_end_date->day
            );
        }

        return null;
    }

    /**
     * @return string
     */
    public function getIntervalAttribute(): string
    {
        return $this->has_interval
            ? sprintf('%s - %s', $this->period_start_date->format('j F'), $this->period_end_date->format('j F'))
            : '';
    }

    /**
     * @param string|null $date
     * @return Date|null
     */
    public function getPeriodStartDateAttribute(string $date = null): ?Date
    {
        return $date
            ? Date::parse($date)
            : null;
    }

    /**
     * @param string|null $date
     * @return Date|null
     */
    public function getPeriodEndDateAttribute(string $date = null): ?Date
    {
        return $date
            ? Date::parse($date)
            : null;
    }

    /**
     * @param string|null $date
     */
    public function setPeriodStartDateAttribute(string $date = null): void
    {
        $this->attributes['period_start_date'] = $date
            ? Date::createFromFormat('d.m', $date)
            : null;
    }

    /**
     * @param string|null $date
     */
    public function setPeriodEndDateAttribute(string $date = null): void
    {
        $this->attributes['period_end_date'] = $date
            ? Date::createFromFormat('d.m', $date)
            : null;
    }
}

app/Http/Controllers/Api/Front/ErrorController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use Illuminate\Http\Request;

class ErrorController extends BaseController
{
    public function __invoke(Request $request)
    {
        $message = sprintf(
            'JS error: referer: %s, message: %s',
            $request->headers->get('referer'),
            $request->input('error')
        );

        notifyMe($message);
        info($message);
    }
}

app/Http/Controllers/Api/Front/TeamController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;

class TeamController extends BaseController
{
}

app/Http/Controllers/Api/Front/TourController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use App\Models\Tour;
use Illuminate\Http\Request;

class TourController extends BaseController
{
    public function index(Request $request)
    {
        $filters = $request->input('filters', []);

        $tours = Tour::with('tournaments.category')
            ->filter($filters)
            ->where('status', '!=', 'created')
            ->get();

        return $this->success(compact('tours'));
    }

    public function show(Tour $tour)
    {
        $tour->load(
            'tournaments.teams.payment',
            'tournaments.teams.users',
            'tournaments.teams.category',
            'tournaments.category'
        );

        return $this->success(compact('tour'));
    }
}

app/Http/Controllers/Api/Front/TournamentController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;

class TournamentController extends BaseController
{
}

app/Http/Controllers/Api/Front/UserController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class UserController extends BaseController
{
    public function index(Request $request)
    {
        $filters = $request->input('filters', []);

        $users = User::filter($filters)
            ->with('category')
            ->get();

        return $this->success(compact('users'));
    }

    public function search(Request $request)
    {
        $users = User::search($request->input('search'))
            ->when($request->input('gender') && in_array($request->input('gender'), ['male', 'female']),
                function (Builder $query) use ($request) {
                    return $query->where('gender', $request->input('gender'));
                })
            ->limit(20)
            ->get();

        $users = $users->transform(function (User $user) {
            return [
                'id'    => $user->id,
                'label' => $user->fullname,
            ];
        });

        return $this->success(compact('users'));
    }
}

app/Http/Controllers/Front/CampController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Camp;
use App\Models\CampReview;
use App\Models\Coach;
use App\Http\Controllers\Controller;

class CampController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $coaches     = Coach::all();
        $futureCamps = Camp::future()->get();
        $pastCamps   = Camp::past()->get();
        $reviews     = CampReview::all();

        return view('front.camps.index', compact('coaches', 'futureCamps', 'pastCamps', 'reviews'));
    }

    /**
     * @param Camp $camp
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Camp $camp)
    {
        return view('front.camps.show', compact('camp'));
    }
}

app/Http/Controllers/Front/EventController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Event;
use App\Models\Location;
use App\Models\Package;
use App\Http\Controllers\Controller;

class EventController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $events   = Event::orderBy('date', 'desc')->with('photos', 'location')->get();
        $packages = Package::orderBy('price')->take(3)->get();

        return view('events.index', compact('events', 'packages'));
    }

    /**
     * @param Event $event
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Event $event)
    {
        return view('events.show', compact('event'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function trainings()
    {
        return view('events.trainings');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function locations()
    {
        $locations = Location::all();

        $data = [
            'Летнее время' => $locations->where('season', 'summer'),
            'Зимнее время' => $locations->where('season', 'winter'),
        ];

        return view('events.locations', compact('data'));
    }

    /**
     * @param Package $package
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function package(Package $package)
    {
        return view('events.package', compact('package'));
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Block;
use App\Models\Coach;
use App\Models\Post;
use App\Models\PostCategory;
use App\Http\Controllers\Controller;
use App\Models\TrainingGroup;

class HomeController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function home()
    {
        $coaches = Coach::all();
        $sliderPosts = Post::latest()->slider()->get();
        $blocks = Block::orderBy('order')->get();

        $posts = [];

        $postCategories = PostCategory::whereIn('url', [
            PostCategory::CATEGORY_TRAINING,
            PostCategory::CATEGORY_CAMPS,
            PostCategory::CATEGORY_TOURNAMENTS,
        ])->get();

        foreach ($postCategories as $category) {
            $posts[$category->id] = Post::latest()
                ->ofCategory($category->id)
                ->take(4)
                ->get();
        }

        // @TODO нутыпонел
        $posts[0] = Post::latest()
            ->take(4)
            ->get();

        $tmpCategory = new PostCategory([
            'id' => 0,
            'url' => 'all',
            'name' => 'Общие новости'
        ]);

        $postCategories->prepend($tmpCategory);

        return view('front.home.index', compact('blocks', 'coaches', 'sliderPosts', 'postCategories', 'posts'));
    }

    public function oplata()
    {
        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.home.oplata', compact('groups'));
    }

    public function individual()
    {
        $coaches = Coach::all();

        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.home.individual', compact('groups', 'coaches'));
    }

    /**
     * @param Coach $coach
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showCoach(Coach $coach)
    {
        return view('front.coaches.show', compact('coach'));
    }
}

app/Http/Controllers/Front/OrderController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Requests\TournamentContributionOrderRequest;
use App\Http\Requests\TrainingOrderRequest;
use App\Models\Payment;
use App\Models\Team;
use App\Services\Tournaments\TournamentService;
use App\Services\Trainings\TrainingService;
use App\Services\YandexKassa;
use Exception;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    private $yandexKassa;

    /**
     * OrderController constructor.
     * @param YandexKassa $yandexKassa
     */
    public function __construct(YandexKassa $yandexKassa)
    {
        $this->yandexKassa = $yandexKassa;
    }

    /**
     * @param TournamentContributionOrderRequest $request
     * @param TournamentService $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function formTournamentContributionOrder(
        TournamentContributionOrderRequest $request, TournamentService $service
    ) {
        /** @var Team $team */
        $team = Team::find($request->get('team_id'));

        if ($team->payment && $team->payment->is_confirmed) {
            return back()->with('warning', 'Взнос уже оплачен.');
        }

        if ($team->tournament->limit_exceeded) {
            return back()->with('warning', 'Прием заявок в эту категорию окончен.');
        }

        if (!$team->payment) {
            $service->createPayment($request->user(), $team);
        } else {
            $service->refreshPayment($team);
        }

        return $this->redirectToYandex($team->payment);
    }

    /**
     * @param TrainingOrderRequest $request
     * @param TrainingService $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function formTrainingOrder(TrainingOrderRequest $request, TrainingService $service)
    {
        $user               = $request->user();
        $trainings          = $request->get('trainings');
        $subscriptionTypeId = $request->get('subscription_type_id');

        try {
            /** @var Payment $payment */
            $payment = $service->createPayment($user, $trainings, $subscriptionTypeId);
        } catch (Exception $e) {
            return back()->with('warning', $e->getMessage());
        }

        return $this->redirectToYandex($payment);
    }

    /**
     * @param Payment $payment
     * @return \Illuminate\Http\RedirectResponse
     */
    private function redirectToYandex(Payment $payment)
    {
        $url = $this->yandexKassa->buildUrl($payment);

        return redirect()->away($url);
    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Page;

class PageController
{
    public function show(Page $page)
    {
        return view('front.pages.show', compact('page'));
    }
}

app/Http/Controllers/Front/PostController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->has('category')) {
            $category = PostCategory::where('url', $request->get('category'))->first();
        }

        $posts= Post::orderBy('created_at', 'desc')
           ->with('category');

        if (isset($category)) {
            $posts->where('category_id', $category->id);
        }

        $posts = $posts->paginate(10);

        if (isset($category)) {
            $posts->appends(['category' => $category->url]);
        }

        return view('posts.index', compact('posts'));
    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        if ($post->id === 969) {
            return redirect()->route('camps.show', 29);
        }

        return view('front.posts.show', compact('post'));
    }
}

app/Http/Controllers/Front/TrainingController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Coach;
use App\Models\TrainingGroup;
use App\Http\Controllers\Controller;

class TrainingController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $coaches = Coach::all();

        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.trainings.index', compact('coaches', 'groups'));
    }

    /**
     * @param TrainingGroup $group
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function purchase(TrainingGroup $group)
    {
        return view('trainings.purchase', compact('group'));
    }
}

app/Http/Controllers/Front/VueContainerController.php
<?php

namespace App\Http\Controllers\Front;

class VueContainerController
{
    public function __invoke()
    {
        return view('front');
    }
}

resources/views/front/home/index.blade.php
@extends('layouts.front.master')

@section('title', 'Клуб и школа пляжного волейбола RIO тренировки для взрослых, начинающих и спортсменов! Волейбольные кэмпы и соревнования!')
@section('description', 'В клубе обучают играющие тренера. Мы тренируем волейбольный Клуб Зенит. Пляжный волейбол.')
@section('keywords', 'Клуб и школа пляжного волейбола RIO тренировки для взрослых, начинающих и спортсменов волейбольные кэмпы и соревнования')

@push('js')
<script src="https://vk.com/js/api/openapi.js"></script>
<script>
    VK.Widgets.Group("vk_groups", {mode: 3, width: "auto", color1: 'FAFAFA', color3: '1B1D7D', color2: '282978'}, 68535444);
</script>
@endpush

@section('content')
<section id="home-info" style="padding-top: 30px;">
    <div class="container no-padding">
        <div class="row" style="margin: 0;">
            <div style="display: flex; align-items: center;">
                <div class="icon logo"></div>
                <div class="grey-divider hidden-xm"></div>
            </div>
            <div class="hidden-xm hidden-sm hidden-xs">
                <h4>Клуб пляжного волейбола</h4>
                <p>Проводим тренировки и все виды соревнований по пляжному волейболу</p>
            </div>
            <div>
                <div style="font-size: 12px; color: #262877;">9:00 - 22:00 без выходных</div>
                <a href="tel:8 (965) 081 04 62" style="font-weight: bold; font-size: 18px; color: #262877 !important;">8 (965) 081 04 62</a>
            </div>
            <a href="#trainings-apply" class="btn btn-warning hidden-xs" onclick="yaCounter31562248.reachGoal('home_write_to_club_click'); return true;">Написать в клуб</a>
        </div>
    </div>
</section>

<section id="home-slider" style="padding-top: 40px;">
    <div class="container no-padding">
        <div id="slider" class="carousel slide" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                @foreach ($sliderPosts as $post)
                    <li data-target="#slider" data-slide-to="{{ $loop->index }}" @if ($loop->first) class="active" @endif></li>
                @endforeach
            </ol>

            <div class="carousel-inner">
                @foreach ($sliderPosts as $post)
                    <div class="item @if ($loop->first) active @endif">
                        <div class="col-md-4">
                            <div class="col-md-12 no-padding">
                                <h2>{{ $post->title }}</h2>
                                <div class="anons">{!! $post->anons !!}</div>
                                <a href="{{ route('posts.show', $post->url) }}" class="btn btn-warning">Подробнее</a>
                            </div>
                        </div>
                        <div class="col-md-8 hidden-sm hidden-xs" style="background: url({{ $post->imageUrl() }}) no-repeat; background-size: cover;"></div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</section>

<section id="home-services" style="padding-top: 70px;">
    <div class="container">
        <div class="row" style="margin: 0 0 35px 0; display: inline-block;">
            <div class="header">
                Услуги волейбольного клуба
            </div>
            <div class="orange-divider"></div>
        </div>
        @foreach ($blocks as $block)
            @if ($loop->index % 3 === 0)
                <div class="row text-center">
            @endif
            <div class="col-sm-4 service">
                <a href="{{ $block->url }}" style="background: url({{ $block->preview_url }}); background-size: cover; width: 100%; height: 250px;display: block;"></a>
                <h4>{{ $block->title }}</h4>
                <p>{{ $block->text }}</p>
                <a href="{{ $block->url }}" class="btn btn-primary">Подробнее</a>
            </div>
            @if ($loop->index % 3 === 2)
                </div>
            @endif
        @endforeach
    </div>
</section>

<section id="home-about" style="padding-bottom: 70px; padding-top: 40px;">
    <div class="container">
        <div class="row">
            <div class="vk col-md-3">
                <div id="vk_groups"></div>
            </div>
            <div class="about col-md-9">
                <div class="text-block">
                    <div class="header">
                        О нас
                    </div>
                    <div class="orange-divider" style="margin-bottom: 40px;"></div>
                    <p style="font-size: 16px; color: #282978; line-height: 26px;">
                        Клуб пляжного волейбола "RIO" создавался на фоне роста популярности пляжного волейбола
                        в Санкт-Петербурге и по всей стране. Питер имеет огромную армию поклонников "бич волея",
                        первых чемпионов России, историю первого чемпионата страны...
                        Задача нашего клуба, не только чтобы эта "армия" росла,
                        но чтобы она еще и "мужала": чтобы качество петербургского пляжного волейбола росло
                        вместе с количеством поклонников.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="home-news" style="padding-bottom: 70px;">
    <div class="container">
        <div class="row" style="margin: 0; display: inline-block;">
            <a class="header" href="/content" style="color: #1b1d7d !important;">
                Новости
            </a>
            <div class="orange-divider" style="margin-bottom: 40px;"></div>
        </div>
        <div class="news-category-selectors">
            <ul>
                @foreach ($postCategories as $category)
                    <li role="presentation" @if ($loop->first) class="active" @endif>
                        <a href="#category-{{ $category->id }}" aria-controls="profile" role="tab" data-toggle="tab">
                            {{ $category->name }}
                        </a>
                    </li>
                @endforeach
            </ul>
            <a class="header text-muted hidden-xs" href="/content" style="color: #777 !important; margin-top: 10px;float: right;font-size: 14px;">
                Подробнее
            </a>
        </div>
        <div class="news-list tab-content">
            @foreach ($postCategories as $category)
                <div role="tabpanel" class="tab-pane @if ($loop->first) active @endif" id="category-{{ $category->id }}">
                    @foreach ($posts[$category->id] as $post)
                        <div class=" post-block">
                            <a href="{{ route('posts.show', $post->url) }}">
                                <img src="{{ $post->imageUrl() }}">
                            </a>
                            <span>{{ $post->localeDate }}</span>
                            <a class="post-title" href="{{ route('posts.show', $post->url) }}">
                                {{ $post->title }}
                            </a>
                        </div>
                    @endforeach
                </div>
            @endforeach
        </div>
    </div>
</section>

<section id="coaches">
    <div class="container">
        <div class="row" style="margin: 0;">
            <div class="header">
                Тренеры
            </div>
            <div class="orange-divider" style="margin-bottom: 20px;"></div>
        </div>
        <div class="coaches">
            @foreach($coaches as $coach)
                <a href="{{ route('coaches.show', $coach) }}" class="coach">
                    <div class="image" style="background-image: url({{ $coach->previewUrl() }});"></div>
                    <div class="text-block">
                        <div class="name">{{ $coach->name }}</div>
                        <div class="description">{{ $coach->status }}</div>
                    </div>
                </a>
            @endforeach
        </div>
    </div>
</section>

@include('front.sponsors')
@include('front.trainings.apply')
@stop

resources/views/front/home/oplata.blade.php
@extends('layouts.front.master')

@section('title', 'Оплата тренировок по пляжному волейболу')
@section('description', 'Оплата тренировок по пляжному волейболу')
@section('keywords', 'Оплата тренировок по пляжному волейболу')

@push('js')
<script src="{{ elixir('js/training_index.js') }}"></script>
<script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
</script>

@endpush

@section('content')
<div id="trainings-index">
    <section id="trainings-schedule" style="padding-top: 70px;">
        <div class="container">
            <div class="row text-center">
                <h1 class="header" style="margin-top: 0;font-weight: normal;">
                    Оплата тренировок по пляжному волейболу
                </h1>
                <div class="orange-divider"></div>
            </div>
            <div class="row" style="margin-bottom: 38px;">
                <div class="col-md-12">
                    <h5>ОБОЗНАЧЕНИЯ:</h5>
                    <div class="icon sun" style="position: relative;top: 11px;margin-left: 21px;margin-right: 8px;"></div>
                    <span class="muted-text">– открытая площадка</span>
                    <div class="icon snow" style="position: relative;top: 10px;margin-left: 61px;margin-right: 8px;"></div>
                    <span class="muted-text">– закрытая площадка</span>
                </div>
            </div>

            <div class="schedule">
                <div class="panel-group" id="accordion" style="margin:25px 0">
                    @foreach ($groups as $group)
                        <div class="hidden fake-toggle" data-toggle="collapse" href="#collapse{{ $group->id }}"></div>
                        <div class="panel panel-default">
                            <div class="panel-heading" data-parent="#accordion">
                                <h4 class="panel-title collapsed" data-toggle="collapse" href="#collapse{{ $group->id }}">
                                    {{ $group->name }}
                                </h4>
                                <div style="display: flex;align-items: center;">
                                    <a class="btn btn-pay" @click="showTrainingApplyModal({{ $group->id }})" style="margin-right: 10px;" onclick="yaCounter31562248.reachGoal('table_apply_click'); return true;">Записаться</a>
                                    <a href="{{ route('trainings.purchase', $group->url) }}" class="btn btn-pay" onclick="yaCounter31562248.reachGoal('table_pay_click'); return true;">
                                        <img src="/front/icons/wallet.svg">
                                        Оплатить
                                    </a>
                                    <div class="circle collapsed" data-toggle="collapse" href="#collapse{{ $group->id }}">
                                        <i class="arrow left"></i>
                                    </div>
                                </div>
                            </div>
                            <div id="collapse{{ $group->id }}" class="panel-collapse collapse" aria-expanded="true">
                                <div class="schedule-weekdays">
                                    <div></div>
                                    <div>Пн</div>
                                    <div>Вт</div>
                                    <div>Ср</div>
                                    <div>Чт</div>
                                    <div>Пт</div>
                                    <div>Сб</div>
                                    <div>Вс</div>
                                </div>
                                @foreach ($group->trainings->groupBy('location_id') as $trainingsByLocation)
                                    @php
                                        $location = $trainingsByLocation->first()->location;
                                    @endphp
                                    <div class="schedule-row">
                                        <div class="schedule-cell">
                                            <div class="icon {{ $location->new_icon }}"></div>
                                            <div class="location-text">
                                                <h4>{{ $location->short_name }}</h4>
                                                <span>{{ $location->address }}</span>
                                            </div>
                                        </div>
                                        @foreach (range(0, 6) as $i)
                                            <div class="schedule-cell">
                                                @if ($trainingsByLocation->groupBy('weekday')->has($i))
                                                    @foreach ($trainingsByLocation->groupBy('weekday')->get($i)->sortBy('start_time') as $training)
                                                        <div data-toggle="popover" data-placement="top" data-trigger="hover" data-html="true"
                                                             title="тренер: {{ $training->coach->name }}"
                                                             data-content="
                                                             @foreach ($training->subscriptionTypes as $type)
                                                                 {{ $type->name }}: {{ $type->pivot->price }}₽
                                                                 @if (!$loop->last)<hr>@endif
                                                             @endforeach
                                                             "
                                                        >
                                                            {{ $training->start_time }} - {{ $training->end_time }}
                                                        </div>
                                                    @endforeach
                                                @endif
                                            </div>
                                        @endforeach
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </section>

    <modal name="trainings-apply-modal" :adaptive="true" :y-pivot="0.2" :width="1170" height="auto">
        <training-apply-form :groups="{{ json_encode($groups) }}" :group_id="modal_group_id"></training-apply-form>
    </modal>
</div>
@stop