app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Date;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Query\Builder;

/**
 * App\Models\Payment
 *
 * @mixin \Eloquent
 * @property-read string $locale_date
 * @property-read string $status_class
 * @property-read string $status_text
 * @property-read Team $team
 * @property-read PaymentType $type
 * @property-read User $user
 * @property-read Collection|UserTraining[] $userTrainings
 * @method static Builder|Payment after($date)
 * @method static Builder|Payment before($date)
 * @method static Builder|Payment confirmed()
 * @method static Builder|Payment filter($filterName)
 * @method static Builder|Payment ofStatus($status)
 * @method static Builder|Payment ofType($paymentTypeId)
 * @method static Builder|Payment search($search)
 * @property int $id
 * @property int $status
 * @property int $invoice_id
 * @property string $comment
 * @property float $sum
 * @property float $order_sum_amount
 * @property float $shop_sum_amount
 * @property string $order_currency
 * @property string $shop_currency
 * @property int $user_id
 * @property int $is_confirmed
 * @property int $is_not_confirmed
 * @property int $payment_type_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class Payment extends Model
{
    use Scopes\Payment;

    protected $table = 'payment';

    const TYPE_TRAINING                = 1;
    const TYPE_TOURNAMENT_CONTRIBUTION = 2;

    const STATUS_CREATED   = 0;
    const STATUS_CHECKED   = 1;
    const STATUS_CONFIRMED = 2;
    const STATUS_CANCELED  = 3;

    public $statuses = [
        self::STATUS_CREATED   => 'создан',
        self::STATUS_CHECKED   => 'проверен',
        self::STATUS_CONFIRMED => 'подтвержден',
        self::STATUS_CANCELED  => 'отменен',
    ];

    public $classes = [
        self::STATUS_CREATED   => 'primary',
        self::STATUS_CHECKED   => 'info',
        self::STATUS_CONFIRMED => 'success',
        self::STATUS_CANCELED  => 'danger',
    ];

    protected $fillable = [
        'payment_type_id',
        'status',
        'comment',
        'sum',
        'order_sum_amount',
        'shop_sum_amount',
        'invoice_id',
    ];

    protected $appends = [
        'is_confirmed'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo|\Illuminate\Database\Eloquent\Builder
     */
    public function type()
    {
        return $this->belongsTo(PaymentType::class, 'payment_type_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo|\Illuminate\Database\Eloquent\Builder
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasOne|\Illuminate\Database\Eloquent\Builder
     */
    public function team()
    {
        return $this->hasOne(Team::class)->withTrashed();
    }

    /**
     * @return HasMany|\Illuminate\Database\Eloquent\Builder
     */
    public function userTrainings()
    {
        /** @var \Illuminate\Database\Eloquent\Builder $relation */
        $relation = $this->hasMany(UserTraining::class);

        return $relation->orderBy('date');
    }

    /**
     * @return string
     */
    public function getLocaleCreatedAtAttribute(): string
    {
        return (new Date($this->created_at))->format('j F Y H:i:s');
    }

    /**
     * @return string
     */
    public function getLocaleUpdatedAtAttribute(): string
    {
        return (new Date($this->updated_at))->format('j F Y H:i:s');
    }

    /**
     * @return string
     */
    public function getStatusTextAttribute(): string
    {
        return $this->statuses[$this->status];
    }

    /**
     * @return string
     */
    public function getStatusClassAttribute(): string
    {
        return $this->classes[$this->status];
    }

    /**
     * @return bool
     */
    public function getIsConfirmedAttribute(): bool
    {
        return $this->status === self::STATUS_CONFIRMED;
    }

    /**
     * @return bool
     */
    public function getIsNotConfirmedAttribute(): bool
    {
        return !$this->is_confirmed;
    }
}

app/Http/Controllers/Api/Front/ErrorController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use Illuminate\Http\Request;

class ErrorController extends BaseController
{
    public function __invoke(Request $request)
    {
        $message = sprintf(
            'JS error: referer: %s, message: %s',
            $request->headers->get('referer'),
            $request->input('error')
        );

        notifyMe($message);
        info($message);
    }
}

app/Http/Controllers/Api/Front/TeamController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;

class TeamController extends BaseController
{
}

app/Http/Controllers/Api/Front/TourController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use App\Models\Tour;
use Illuminate\Http\Request;

class TourController extends BaseController
{
    public function index(Request $request)
    {
        $filters = $request->input('filters', []);

        $tours = Tour::with('tournaments.category')
            ->filter($filters)
            ->where('status', '!=', 'created')
            ->get();

        return $this->success(compact('tours'));
    }

    public function show(Tour $tour)
    {
        $tour->load(
            'tournaments.teams.payment',
            'tournaments.teams.users',
            'tournaments.teams.category',
            'tournaments.category'
        );

        return $this->success(compact('tour'));
    }
}

app/Http/Controllers/Api/Front/TournamentController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;

class TournamentController extends BaseController
{
}

app/Http/Controllers/Api/Front/UserController.php
<?php

namespace App\Http\Controllers\Api\Front;

use App\Http\Controllers\Api\BaseController;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class UserController extends BaseController
{
    public function index(Request $request)
    {
        $filters = $request->input('filters', []);

        $users = User::filter($filters)
            ->with('category')
            ->get();

        return $this->success(compact('users'));
    }

    public function search(Request $request)
    {
        $users = User::search($request->input('search'))
            ->when($request->input('gender') && in_array($request->input('gender'), ['male', 'female']),
                function (Builder $query) use ($request) {
                    return $query->where('gender', $request->input('gender'));
                })
            ->limit(20)
            ->get();

        $users = $users->transform(function (User $user) {
            return [
                'id'    => $user->id,
                'label' => $user->fullname,
            ];
        });

        return $this->success(compact('users'));
    }
}

app/Http/Controllers/Front/CampController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Camp;
use App\Models\CampReview;
use App\Models\Coach;
use App\Http\Controllers\Controller;

class CampController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $coaches     = Coach::all();
        $futureCamps = Camp::future()->get();
        $pastCamps   = Camp::past()->get();
        $reviews     = CampReview::all();

        return view('front.camps.index', compact('coaches', 'futureCamps', 'pastCamps', 'reviews'));
    }

    /**
     * @param Camp $camp
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Camp $camp)
    {
        return view('front.camps.show', compact('camp'));
    }
}

app/Http/Controllers/Front/EventController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Event;
use App\Models\Location;
use App\Models\Package;
use App\Http\Controllers\Controller;

class EventController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $events   = Event::orderBy('date', 'desc')->with('photos', 'location')->get();
        $packages = Package::orderBy('price')->take(3)->get();

        return view('events.index', compact('events', 'packages'));
    }

    /**
     * @param Event $event
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Event $event)
    {
        return view('events.show', compact('event'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function trainings()
    {
        return view('events.trainings');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function locations()
    {
        $locations = Location::all();

        $data = [
            'Летнее время' => $locations->where('season', 'summer'),
            'Зимнее время' => $locations->where('season', 'winter'),
        ];

        return view('events.locations', compact('data'));
    }

    /**
     * @param Package $package
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function package(Package $package)
    {
        return view('events.package', compact('package'));
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Block;
use App\Models\Coach;
use App\Models\Post;
use App\Models\PostCategory;
use App\Http\Controllers\Controller;
use App\Models\TrainingGroup;

class HomeController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function home()
    {
        $coaches = Coach::all();
        $sliderPosts = Post::latest()->slider()->get();
        $blocks = Block::orderBy('order')->get();

        $posts = [];

        $postCategories = PostCategory::whereIn('url', [
            PostCategory::CATEGORY_TRAINING,
            PostCategory::CATEGORY_CAMPS,
            PostCategory::CATEGORY_TOURNAMENTS,
        ])->get();

        foreach ($postCategories as $category) {
            $posts[$category->id] = Post::latest()
                ->ofCategory($category->id)
                ->take(4)
                ->get();
        }

        // @TODO нутыпонел
        $posts[0] = Post::latest()
            ->take(4)
            ->get();

        $tmpCategory = new PostCategory([
            'id' => 0,
            'url' => 'all',
            'name' => 'Общие новости'
        ]);

        $postCategories->prepend($tmpCategory);

        return view('front.home.index', compact('blocks', 'coaches', 'sliderPosts', 'postCategories', 'posts'));
    }

    public function oplata()
    {
        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.home.oplata', compact('groups'));
    }

    public function individual()
    {
        $coaches = Coach::all();

        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.home.individual', compact('groups', 'coaches'));
    }

    /**
     * @param Coach $coach
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function showCoach(Coach $coach)
    {
        return view('front.coaches.show', compact('coach'));
    }
}

app/Http/Controllers/Front/OrderController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Requests\TournamentContributionOrderRequest;
use App\Http\Requests\TrainingOrderRequest;
use App\Models\Payment;
use App\Models\Team;
use App\Services\Tournaments\TournamentService;
use App\Services\Trainings\TrainingService;
use App\Services\YandexKassa;
use Exception;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    private $yandexKassa;

    /**
     * OrderController constructor.
     * @param YandexKassa $yandexKassa
     */
    public function __construct(YandexKassa $yandexKassa)
    {
        $this->yandexKassa = $yandexKassa;
    }

    /**
     * @param TournamentContributionOrderRequest $request
     * @param TournamentService $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function formTournamentContributionOrder(
        TournamentContributionOrderRequest $request, TournamentService $service
    ) {
        /** @var Team $team */
        $team = Team::find($request->get('team_id'));

        if ($team->payment && $team->payment->is_confirmed) {
            return back()->with('warning', 'Взнос уже оплачен.');
        }

        if ($team->tournament->limit_exceeded) {
            return back()->with('warning', 'Прием заявок в эту категорию окончен.');
        }

        if (!$team->payment) {
            $service->createPayment($request->user(), $team);
        } else {
            $service->refreshPayment($team);
        }

        return $this->redirectToYandex($team->payment);
    }

    /**
     * @param TrainingOrderRequest $request
     * @param TrainingService $service
     * @return \Illuminate\Http\RedirectResponse
     */
    public function formTrainingOrder(TrainingOrderRequest $request, TrainingService $service)
    {
        $user               = $request->user();
        $trainings          = $request->get('trainings');
        $subscriptionTypeId = $request->get('subscription_type_id');

        try {
            /** @var Payment $payment */
            $payment = $service->createPayment($user, $trainings, $subscriptionTypeId);
        } catch (Exception $e) {
            return back()->with('warning', $e->getMessage());
        }

        return $this->redirectToYandex($payment);
    }

    /**
     * @param Payment $payment
     * @return \Illuminate\Http\RedirectResponse
     */
    private function redirectToYandex(Payment $payment)
    {
        $url = $this->yandexKassa->buildUrl($payment);

        return redirect()->away($url);
    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Page;

class PageController
{
    public function show(Page $page)
    {
        return view('front.pages.show', compact('page'));
    }
}

app/Http/Controllers/Front/PostController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($request->has('category')) {
            $category = PostCategory::where('url', $request->get('category'))->first();
        }

        $posts= Post::orderBy('created_at', 'desc')
           ->with('category');

        if (isset($category)) {
            $posts->where('category_id', $category->id);
        }

        $posts = $posts->paginate(10);

        if (isset($category)) {
            $posts->appends(['category' => $category->url]);
        }

        return view('posts.index', compact('posts'));
    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        if ($post->id === 969) {
            return redirect()->route('camps.show', 29);
        }

        return view('front.posts.show', compact('post'));
    }
}

app/Http/Controllers/Front/TrainingController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Coach;
use App\Models\TrainingGroup;
use App\Http\Controllers\Controller;

class TrainingController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $coaches = Coach::all();

        $groups = TrainingGroup::has('trainings')
            ->with('trainings.subscriptionTypes', 'trainings.coach', 'trainings.location')
            ->sorted()
            ->get();

        return view('front.trainings.index', compact('coaches', 'groups'));
    }

    /**
     * @param TrainingGroup $group
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function purchase(TrainingGroup $group)
    {
        return view('trainings.purchase', compact('group'));
    }
}

app/Http/Controllers/Front/VueContainerController.php
<?php

namespace App\Http\Controllers\Front;

class VueContainerController
{
    public function __invoke()
    {
        return view('front');
    }
}

resources/views/front/profile/edit.blade.php
@extends('layouts.front.master')

@section('title', 'Редактирование данных')

{{--<div class="ui vertical fluid pointing secondary menu">--}}
    {{--<a class="item {{ Route::is('auth.profile.trainings') ? 'active' : '' }}" href="{{ route('auth.profile.trainings') }}">--}}
        {{--Тренировки--}}
    {{--</a>--}}
    {{--<a class="item {{ Route::is('auth.profile.payments') ? 'active' : '' }}" href="{{ route('auth.profile.payments') }}">--}}
        {{--Платежи--}}
    {{--</a>--}}
    {{--<a class="item {{ Route::is('auth.profile.edit') ? 'active' : '' }}" href="{{ route('auth.profile.edit') }}">--}}
        {{--Редактирование данных--}}
    {{--</a>--}}
    {{--<a class="item {{ Route::is('auth.profile.feedback') ? 'active' : '' }}" href="{{ route('auth.profile.feedback') }}">--}}
        {{--Обратная связь--}}
    {{--</a>--}}
{{--</div>--}}

@push('css')
    <link rel="stylesheet" type="text/css" href="/datepicker/daterangepicker.min.css">
@endpush

@section('content')
    <form method="POST" class="ui form profile-form" action="{{ route('auth.profile.update') }}">
        @include('layouts.front.errors')

        {{ csrf_field() }}

        <div class="two fields">
            <div class="field left aligned">
                <label for="name">Фамилия</label>
                <input type="text" name="surname" placeholder="Фамилия" value="{{ $user->surname }}">
            </div>
            <div class="field">
                <label for="name">Имя</label>
                <input type="text" name="name" placeholder="Имя" value="{{ $user->name }}">
            </div>
        </div>
        <div class="field">
            <label for="name">Дата рождения</label>
            <input type="text" name="birth_date" placeholder="Дата рождения" value="{{ $user->birth_date }}">
        </div>
        <div class="two fields">
            <div class="field">
                <label for="name">Рост, см</label>
                <input type="text" name="height" placeholder="Рост, см" value="{{ $user->height }}">
            </div>
            <div class="field">
                <label for="name">Вес, кг</label>
                <input type="text" name="weight" placeholder="Вес, кг" value="{{ $user->weight }}">
            </div>
        </div>
        <div class="field">
            <label for="name">Хобби</label>
            <input type="text" name="hobby" placeholder="Хобби" value="{{ $user->hobby }}">
        </div>

        <div class="ui primary submit button">
            Сохранить
        </div>
    </form>
@stop

@push('javascript')
    <script src="/bower/moment/min/moment.min.js"></script>
    <script src="/datepicker/daterangepicker.min.js"></script>
    <script>
        $(document).ready(function() {
            $(function() {
                $('input[name="birth_date"]').daterangepicker({
                    singleDatePicker: true,
                    showDropdowns: true,
                    format: 'YYYY-MM-DD',
                });
            });

            $('.profile-form').form({
                fields: {
                    surname     : {
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Введите фамилию'
                            }
                        ]
                    },
                    name     : {
                        rules: [
                            {
                                type   : 'empty',
                                prompt : 'Введите имя'
                            }
                        ]
                    },
                    height: {
                        optional: true,
                        rules: [
                            {
                                type   : 'integer',
                                prompt : 'Рост должен быть числом'

                            }
                        ]
                    },
                    weight: {
                        optional: true,
                        rules: [
                            {
                                type   : 'integer',
                                prompt : 'Вес должен быть числом'

                            }
                        ]
                    },
                }
            });
        });
    </script>
@endpush

resources/views/front/profile/feedback.blade.php
@extends('layouts.front.master')

@section('title', 'Обратная связь')

@section('content')
    <form method="POST" class="ui form" action="{{ route('auth.profile.feedback.send') }}">
        @include('layouts.partials.errors')

        {{ csrf_field() }}

        <div class="field">
            <label for="name">Сообщение</label>
            <textarea name="text" required>{{ old('text') }}</textarea>
        </div>

        <button class="ui primary submit button">
            Отправить
        </button>
    </form>
@stop

resources/views/front/profile/payments.blade.php
@extends('layouts.front.master')

@section('title', 'Платежи')

@section('content')
    @if(!$payments->isEmpty())
        <table class="ui celled table">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Сумма</th>
                    <th>Тип платежа</th>
                    <th>Дата</th>
                </tr>
            </thead>
            @foreach($payments as $payment)
                <tr>
                    <td>#{{ $payment->id }}</td>
                    <td>{{ $payment->sum }} ₽</td>
                    <td>{{ $payment->type->name }}</td>
                    <td>{{ $payment->locale_created_at }}</td>
                </tr>
            @endforeach
        </table>
        {{ $payments->links() }}
    @else
        <div class="ui blue message large">У вас нет платежей</div>
    @endif
@endsection

resources/views/front/profile/show.blade.php
@extends('layouts.front.master')

@section('title', $user->surname . ' ' . $user->name)

@section('nwtour_content')
    <div class="ui segment grid stackable profile-show">
        <div class="column nine wide">
            <div class="ui header">
                {{ $user->surname }} {{ $user->name }}
            </div>
            <span>
                {{ $user->ageAndBirthDate() }}
            </span>
        </div>
        <div class="column seven wide">
            @if ($user->height)
                <div>Рост: {{ $user->height }}см</div>
            @endif
            @if ($user->weight)
                <div>Вес: {{ $user->weight }}кг</div>
            @endif
            @if ($user->hobby)
                <div>Хобби: {{ $user->hobby }}</div>
            @endif
        </div>
    </div>

    @unless ($teams->isEmpty())
        <div style="overflow-x: auto">
            <table class="ui small slim table unstackable">
                <thead style="font-size: 0.8em;">
                    <th>Дата</th>
                    <th>Этап</th>
                    <th>Кат.</th>
                    <th>Партнер</th>
                    <th>Место</th>
                    <th>Рейтинг</th>
                </thead>
                <tbody>
                    @foreach ($teams as $team)
                        <tr>
                            <td>{{ $team->tournament->nwtour->localeDate }}</td>
                            <td>
                                <a href="{{ route('nwtour.info', $team->tournament->nwtour->id) }}">
                                    {{ $team->tournament->nwtour->title }}
                                </a>
                            </td>
                            <td>
                                {{ $team->tournament->category->name }}
                            </td>
                            <td>
                                {!! $team->usersLinks($user->id) !!}
                            </td>
                            <td>
                                {{ $team->rank }}
                            </td>
                            <td>
                                {{ $team->rating/$team->tournament->category->team_size }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endunless
@stop

resources/views/front/profile/trainings.blade.php
@extends('layouts.front.master')

@section('title', 'Оплаченные тренировки')

@section('content')
    @if(!$trainings->isEmpty())
        <table class="ui celled table">
            <thead>
            <tr>
                <th>Дата</th>
                <th>Время</th>
                <th>Тренер</th>
                <th>Место</th>
            </tr>
            </thead>
            @foreach($trainings as $training)
                <tr class="{{ $training->date->isToday() ? 'positive' : ($training->date->isPast() ? 'disabled' : '') }}">
                    <td>{{ $training->localeDate }}</td>
                    <td>{{ $training->start_time }} - {{ $training->end_time }}</td>
                    <td>
                        <a href="{{ route('coaches.show', $training->coach) }}">
                            {{ $training->coach->name ?? '' }}
                        </a>
                    </td>
                    <td>{{ $training->location->short_name ?? '' }}</td>
                </tr>
            @endforeach
        </table>

        {{ $trainings->links() }}
    @else
        <div class="ui blue message large">У вас нет оплаченных тренировок</div>
    @endif
@endsection